const data = [
  {
    id: '00000157-0797-d6f0-a7ff-e7ff97ee0026',
    name: 'Annual Membership - Monumental Sports Network',
    description: 'Annual Membership',
    identifier: 'annual2016dead',
    monetizationModel: 'SVOD',
    planDetails: [
      {
        title: null,
        description: null,
        countryCode: 'US',
        visible: true,
        displayStrikeThroughPrice: false,
        hidePlanPrice: false,
        isDefault: true,
        isPurchaseEnabled: false,
        purchaseAmount: null,
        isRentEnabled: false,
        numberOfAllowedStreams: 5,
        numberOfAllowedDevices: 10,
        recurringPaymentAmount: 106.99,
        recurringPaymentCurrencyCode: 'USD',
        redirectUrl: '',
        rentAmount: null,
        rentalPeriodUnit: null,
        rentalPeriodValue: null,
        featureDetails: [
          {
            textToDisplay: 'Save over 30% Off Monthly Plan',
            value: 'true',
            valueType: 'boolean',
          },
          {
            textToDisplay: 'Single Payment',
            value: 'true',
            valueType: 'boolean',
          },
          {
            textToDisplay: 'Paid Annually',
            value: 'true',
            valueType: 'boolean',
          },
          {
            textToDisplay: 'Unlimited Access',
            value: 'true',
            valueType: 'boolean',
          },
        ],
        supportedDevices: [
          'android_tablet',
          'web_browser',
          'ios_ipad',
          'ios_phone',
          'android_phone',
          'ios_apple_tv',
          'roku_box',
        ],
        channel_ids: [],
        taxIncluded: null,
      },
    ],
    planDisplayOrder: null,
    renewable: true,
    renewalCyclePeriodMultiplier: 1,
    renewalCycleType: 'YEAR',
    featureSetting: {
      includingAds: true,
      isBeamingAllowed: true,
      isHdStreaming: true,
      isDownloadAllowed: true,
      numberOfAllowedDevices: 10,
      numberOfAllowedStreams: 5,
      contentConsumption: ['web', 'ios', 'android', 'roku', 'fireTv', 'appleTv', 'samsung', 'lg', 'androidTv', 'tivo'],
      isLoginRequired: false,
    },
    metadata: null,
  },
  {
    id: 'ff27b3b0-0dbd-4b64-b38a-c6ee20544e9a',
    name: 'Monumental Membership',
    description: 'Monumental Membership Plan',
    identifier: 'msnannual2023',
    monetizationModel: 'SVOD',
    planDetails: [
      {
        title: 'Monumental Membership',
        description: 'Monumental Membership',
        countryCode: 'US',
        visible: true,
        displayStrikeThroughPrice: false,
        hidePlanPrice: false,
        isDefault: true,
        isPurchaseEnabled: false,
        purchaseAmount: null,
        isRentEnabled: false,
        numberOfAllowedStreams: 1000,
        numberOfAllowedDevices: 1000,
        recurringPaymentAmount: 199.99,
        recurringPaymentCurrencyCode: 'USD',
        redirectUrl: '',
        rentAmount: null,
        rentalPeriodUnit: null,
        rentalPeriodValue: null,
        featureDetails: [
          {
            textToDisplay: 'Stream on three devices at once',
            value: '3',
            valueType: 'number',
          },
          {
            textToDisplay: '20% discount off team merchandise & apparel',
            value: 'Y',
            valueType: 'string',
          },
          {
            textToDisplay: 'Discounted tickets for select Game of the Month',
            value: 'Y',
            valueType: 'string',
          },
          {
            textToDisplay:
              'Watch live in-market Capitals, Wizards, Mystics and Go-Go games (regional viewing restrictions apply)',
            value: 'Y',
            valueType: 'string',
          },
        ],
        supportedDevices: [
          'android_tablet',
          'android_tv',
          'oneplus_tv',
          'web_browser',
          'ios_ipad',
          'ios_phone',
          'android_phone',
          'ios_apple_tv',
          'roku_box',
          'fire_tv',
          'smart_tv_samsung',
          'smart_tv_lg',
          'windows_xbox',
          'corpus',
          'vizioTv',
          'xfinityX1',
        ],
        channel_ids: [],
        taxIncluded: null,
      },
    ],
    planDisplayOrder: 1,
    renewable: true,
    renewalCyclePeriodMultiplier: 1,
    renewalCycleType: 'YEAR',
    featureSetting: {
      includingAds: false,
      isBeamingAllowed: true,
      isHdStreaming: true,
      isDownloadAllowed: true,
      numberOfAllowedDevices: 1000,
      numberOfAllowedStreams: 1000,
      contentConsumption: [
        'web',
        'ios',
        'android',
        'roku',
        'fireTv',
        'appleTv',
        'samsung',
        'lg',
        'androidTv',
        'tivo',
        'miTv',
        'corpus',
        'vizioTv',
        'xBox',
        'xfinityX1',
      ],
      isLoginRequired: false,
    },
    metadata: [
      {
        name: 'planBoxOffer',
        value: 'Save 15%',
      },
      {
        name: 'planInfoOffer',
        value: 'Save 15% compared to monthly plan',
      },
      {
        name: 'vl_payment_vizio_us',
        value: 'myoutdoortv-5',
      },
    ],
  },
  {
    id: '4bb09852-d520-4da2-a546-43a2db1f2bee',
    name: 'Monthly Plan',
    description: 'Monthly Plan',
    identifier: 'msnmonthly2023',
    monetizationModel: 'SVOD',
    planDetails: [
      {
        title: 'Monthly Plan',
        description: 'Monthly Plan',
        countryCode: 'US',
        visible: true,
        displayStrikeThroughPrice: false,
        hidePlanPrice: false,
        isDefault: true,
        isPurchaseEnabled: false,
        purchaseAmount: null,
        isRentEnabled: false,
        numberOfAllowedStreams: 1000,
        numberOfAllowedDevices: 1000,
        recurringPaymentAmount: 19.99,
        recurringPaymentCurrencyCode: 'USD',
        redirectUrl: '',
        rentAmount: null,
        rentalPeriodUnit: null,
        rentalPeriodValue: null,
        featureDetails: [
          {
            textToDisplay: 'Stream on one device at a time',
            value: '1',
            valueType: 'number',
          },
          {
            textToDisplay: '20% discount off team merchandise & apparel',
            value: 'N',
            valueType: 'string',
          },
          {
            textToDisplay: 'Discounted tickets for select Game of the Month',
            value: 'N',
            valueType: 'string',
          },
          {
            textToDisplay:
              'Watch live in-market Capitals, Wizards, Mystics and Go-Go games (regional viewing restrictions apply)',
            value: 'Y',
            valueType: 'string',
          },
        ],
        supportedDevices: [
          'android_tablet',
          'android_tv',
          'oneplus_tv',
          'web_browser',
          'ios_ipad',
          'ios_phone',
          'android_phone',
          'ios_apple_tv',
          'roku_box',
          'fire_tv',
          'smart_tv_samsung',
          'smart_tv_lg',
          'windows_xbox',
          'corpus',
          'vizioTv',
          'xfinityX1',
        ],
        channel_ids: [],
        taxIncluded: null,
      },
    ],
    planDisplayOrder: 2,
    renewable: true,
    renewalCyclePeriodMultiplier: 1,
    renewalCycleType: 'MONTH',
    featureSetting: {
      includingAds: false,
      isBeamingAllowed: true,
      isHdStreaming: true,
      isDownloadAllowed: true,
      numberOfAllowedDevices: 1000,
      numberOfAllowedStreams: 1000,
      contentConsumption: [
        'web',
        'ios',
        'android',
        'roku',
        'fireTv',
        'appleTv',
        'samsung',
        'lg',
        'androidTv',
        'tivo',
        'miTv',
        'corpus',
        'vizioTv',
        'xBox',
        'xfinityX1',
      ],
      isLoginRequired: false,
    },
    metadata: [
      {
        name: 'vl_payment_vizio_us',
        value: 'myoutdoortv-4',
      },
    ],
  },
];

export default data;
